version: '3.8'

services:
  wuzapi:
    build: ./wuzapi
    container_name: wuzapi
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./wuzapi_data:/app/dbdata
    restart: always

  bot-app:
    build: ./bot-app
    container_name: bot-app
    depends_on:
      - wuzapi
    ports:
      - "3000:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./bot-app:/var/www/html