version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: evolution_db
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: evolution_redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
    restart: always

  evolution-api:
    build: ./evolution-api-src
    container_name: evolution_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./evolution_instances:/evolution/instances
    restart: always

  bot-app:
    build: ./bot-app
    container_name: bot-app
    depends_on:
      - evolution_api
    ports:
      - "3000:8080"
    env_file:
      - .env
    restart: always